name: Security Pipeline

on:
  push:
  pull_request:

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # -------------------------
      # Run Bandit on Python Code
      # -------------------------
      - name: Install Bandit
        run: |
          bandit -r . --severity-level medium --confidence-level medium -f txt -o bandit-report.txt

      - name: Run Bandit Scan
        run: bandit -r .

      # -------------------------
      # Build Docker Image
      # -------------------------
      - name: Build Docker image
        run: docker build -t insecure-app .

      # -------------------------
      # Run Trivy on Docker Image
      # -------------------------
      - name: Install Trivy
        uses: aquasecurity/trivy-action@master

      - name: Scan Docker image with Trivy
        run: trivy image insecure-app
