name: Security Pipeline

on:
  push:
  pull_request:

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # -------------------------
      # Run Bandit on Python Code
      # -------------------------
      - name: Install Bandit
        run: pip install bandit
         
      - name: Run Bandit Scan
        run: bandit -r . || true

      # -------------------------
      # Build Docker Image
      # -------------------------
      - name: Build Docker image
        run: docker build -t insecure-app .

      # -------------------------
      # Run Trivy on Docker Image
      # -------------------------
      - name: Install Trivy
        uses: aquasecurity/trivy-action@master

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
           image-ref: insecure-app
